includes:
  - config/classification/models/mrm.yml

name: classification_nih
ckpt_dir: ckpt

dataset:
  proto: NIH_Dataset
  imgpath: /raid/zhouyang/DATA/NIH_ChestX-ray/all_classes
  views: ["PA", "AP"]
  data_pct: 0.01

transforms:
  type: NIHTransforms

model:
  proto: ImageClassifier

  cnn:
    num_classes: 14  # enable classifier layer
    output_layer: avgpool
    global_pool: avg

  classifier:
    proto: Identity
    # input_size: 768 # overwritten
    # num_classes: 14 # use ViT classifier layer

  loss:
    proto: BCEWithLogitsLoss

trainer:
  optimizer: SGD
  optim_params:
    lr: 3e-2
    momentum: 0.9
    weight_decay: 0 
  batch_size: 96
  clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 50
    t_total: 3000
  epochs: 300
  early_stop: 10
  eval_start: 60
  eval_interval: 1
  early_stop_metric: multilabel_auroc

validator:
  batch_size: 512
  metrics: [multilabel_auroc]
  splits: [valid]