includes:
  - config/multiclass_classification/models/gloria.yml

name: classification_nih
ckpt_dir: ckpt

dataset:
  proto: TBX11K_Dataset  # change to multiclass dataset for testing
  imgpath: /raid/zhouyang/DATA/tbx11k-simplified/images
  csvpath: /raid/zhouyang/DATA/tbx11k-simplified/data.csv
  # num_workers: 0

transforms:
  type: NIHTransforms

model:
  proto: ImageClassifier

  cnn:
    output_layer: avgpool

  classifier:
    proto: Classifier
    # input_size: 768 # overwritten
    num_classes: 3 # modify according to dataset
    dropout: 0.

  loss:
    proto: CrossEntropyLoss

trainer:
  optimizer: Adam
  optim_params:
    lr: 0.0001
    eps: 1e-08
    weight_decay: 1e-5
  batch_size: 96
  clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 50
    t_total: 3000
  epochs: 50
  early_stop: 10
  eval_start: 10
  eval_interval: 5
  early_stop_metric: multiclass_auroc

validator:
  batch_size: 512
  metrics: [multiclass_accuracy, multiclass_auroc]
  splits: [valid]