includes:
  - config/multilabel_classification/models/refers.yml

name: classification_nih
ckpt_dir: ckpt

dataset:
  proto: NIH_Dataset
  imgpath: /home/ubuntu/MRM-pytorch/Datasets/NIH_ChestX-ray/all_classes
  views: ["PA", "AP"]
  data_pct: 0.1

transforms:
  type: NIHTransforms

model:
  proto: ImageClassifier

  cnn:
    # output_layer: avgpool
    num_classes: 14
    zero_head: True
    prelogits: False
    

  classifier:
    proto: Identity
    # input_size: 768 # overwritten
    # num_classes: 14
    # dropout: 0.

  loss:
    proto: CrossEntropyLoss

trainer:
  optimizer: SGD
  optim_params:
    lr: 3e-2  # try 1e-4
    momentum: 0.9
    weight_decay: 0
  batch_size: 96
  # clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 50
    t_total: 3000
  epochs: 300
  early_stop: 10
  eval_start: 30
  eval_interval: 5
  early_stop_metric: multiclass_auroc

validator:
  batch_size: 512
  metrics: [multiclass_accuracy, multiclass_auroc]
  splits: [valid]