name: mgca_resnet50

model:
  cnn:
    proto: VisualEncoder
    backbone: resnet50
    pretrained: /home/faith/unified-framework/ckpt/pretrained/MGCA_ResNet.ckpt
    prefix: img_encoder_q.model.
    output_layer: layer4 # do not return fc layer
    dropout_out: 0.0
    permute: batch_first
    freeze: False

  fusion: # for MMVQA
    input_image_embed_size: 2048

  transformer: # for RRG
    d_vf: 2048

  classifier: # for CLS
    input_size: 2048