name: gloria

model:
  cnn:
    proto: VisualEncoder
    backbone: resnet50
    pretrained: /home/faith/unified-framework/ckpt/official/GLoRIA.ckpt
    prefix: gloria.img_encoder.model.
    output_layer: layer4 # change to avgpool for zero-shot
    dropout_out: 0.0
    permute: batch_first
    freeze: False

    #####  Uncomment below for zero-shot and cls  #####
    # visual_projection: 
    #   layer: >
    #     nn.Linear(2048, 768)
    #   prefix: gloria.img_encoder.global_embedder.

  # language: # for zero-shot experiments
  #   proto: emilyalsentzer/Bio_ClinicalBERT
  #   pretrained: /home/faith/unified-framework/ckpt/pretrained/GLoRIA.pth
  #   prefix: linguistic.encoder.

  fusion: # for MMVQA
    input_image_embed_size: 2048

  transformer: # for RRG
    d_vf: 2048

  classifier: # for CLS
    input_size: 2048