name: medclip_resnet50

model:
  cnn:
    proto: VisualEncoder
    backbone: resnet50
    pretrained: /content/drive/MyDrive/A*STAR Internship/Checkpoints/MedCLIP-resnet50.bin
    prefix: vision_model.model.
    output_layer: layer4 # change to avgpool for zero-shot
    dropout_out: 0.0
    permute: batch_first
    freeze: False

    #####  Uncomment below for zero-shot and cls  #####
    visual_projection: 
      layer: >
        nn.Linear(2048, 512, bias=False)
      prefix: visual_model.model.fc.

  fusion: # for MMVQA
    input_image_embed_size: 2048

  transformer: # for RRG
    d_vf: 2048

  classifier: # for CLS
    input_size: 2048