name: mgca_vit

model:
  cnn:
    proto: VisualEncoder
    backbone: timmvit
    pretrained: /home/faith/unified-framework/ckpt/official/MGCA-vit.ckpt
    prefix: img_encoder_q.model.
    dropout_out: 0.0
    permute: no_permute
    freeze: False

  fusion: # for MMVQA
    input_image_embed_size: 768