name: mrm

model:
  cnn:
    proto: VisualEncoder
    backbone: timmvit
    pretrained: /home/faith/unified-framework/ckpt/official/MRM.pth # no prefix
    dropout_out: 0.0
    drop_path_rate: 0.1
    freeze: False

  fusion: # for MMVQA
    input_image_embed_size: 768

  transformer: # for RRG
    d_vf: 768

  classifier: # for CLS
    input_size: 768