name: refers

model:
  cnn:
    proto: REFERSViT
    config_name: ViT-B_16
    pretrained: /home/faith/unified-framework/ckpt/official/REFERS.pth # no prefix
    num_classes: 0 # set 0 classes to retrieve last hidden state
    prelogits: True

  fusion: # for MMVQA
    input_image_embed_size: 768

  transformer: # for RRG
    d_vf: 768

  classifier: # for CLS
    input_size: 768