includes:
  - config/templates/finetune/models/mflag.yml

name: Our_MFLAG
ckpt_dir: experiments/classification/padchest/
use_amp: True
seed: 42

dataset:
  proto: PC_Dataset
  data_path: /home/users/astar/ares/zhouy2/scratch/processed_data/PadChest
  csvpath: /home/users/astar/ares/zhouy2/scratch/processed_data/PadChest/padchest_labels.csv
  views: ["PA", "AP"]
  split: "train_1"
  num_workers: 4

transforms:
  type: NIHTransforms

pretrained_source: custom
pretrained_path:
  official: /home/users/astar/ares/zhouy2/scratch/BenchX/ckpt/official/M-FLAG_total.pth # Not Aavailable
  custom: /home/users/astar/ares/zhouy2/scratch/BenchX/ckpt/pretrained/M-FLAG_total.pth
pretrained_prefix:
  official: encoder.
  custom: encoder.

model:
  proto: ImageClassifier

  cnn:
    output_layer: avgpool
    pretrained: ${pretrained_path.${pretrained_source}}
    prefix: ${pretrained_prefix.${pretrained_source}}
    freeze: False

  classifier:
    proto: Classifier
    # input_size: 2048 # overwritten
    num_classes: 28
    dropout: 0.
    use_fc_norm: True
    trunc_init: True

  loss:
    proto: BCEWithLogitsLoss

trainer:
  optimizer: Adam
  optim_params:
    lr: 1e-4
    eps: 1e-08
    # weight_decay: 1e-5
  batch_size: 64
  clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 50
    t_total: 3000
  epochs: 200
  early_stop: 10
  eval_start: 10
  eval_interval: 5
  early_stop_metric: multilabel_auroc

validator:
  batch_size: 512
  metrics: [multilabel_auroc]
  splits: [val]