name: mflag

model:
  cnn:
    proto: VisualEncoder
    backbone: resnet50
    pretrained: /home/faith/unified-framework/ckpt/pretrained/M-FLAG_total.pth
    prefix: encoder.
    output_layer: avgpool
    dropout_out: 0.0
    permute: batch_first
    freeze: False

    visual_projection: 
      layer: >
        nn.Sequential(
          nn.Linear(2048, 2048),
            nn.BatchNorm1d(2048),
            nn.ReLU(inplace=True),
            nn.Linear(2048, 1024),
            nn.BatchNorm1d(1024, affine=False))
      prefix: proj_v.

  language: # for zero-shot experiments
    proto: microsoft/BiomedVLP-CXR-BERT-general
    pretrained: /home/faith/unified-framework/ckpt/pretrained/M-FLAG_total.pth
    prefix: lm_model.

    language_projection:
      layer: >
        nn.Sequential(
            nn.Linear(768, 2048),
            nn.BatchNorm1d(2048),
            nn.ReLU(inplace=True),
            nn.Linear(2048, 1024),
            nn.BatchNorm1d(1024, affine=False))
      prefix: proj_t.