includes:
  - config/templates/finetune/models/convirt.yml

name: Our_ConVIRT
ckpt_dir: experiments/classification/vindr/
use_amp: True
seed: 42

dataset:
  proto: VinDr_Dataset
  data_path: /home/users/astar/ares/zhouy2/scratch/processed_data/Vindr_CXR_512/
  csvpath: /home/users/astar/ares/zhouy2/scratch/processed_data/Vindr_CXR_512/vindr_labels.csv
  split: "train_1"
  num_workers: 4

transforms:
  type: NIHTransforms

pretrained_source: custom
pretrained_path:
  official: /home/users/astar/ares/zhouy2/scratch/BenchX/ckpt/official/ConVIRT.pth
  custom: /home/users/astar/ares/zhouy2/scratch/BenchX/ckpt/pretrained/ConVIRT.pth

model:
  proto: ImageClassifier

  cnn:
    output_layer: avgpool
    pretrained: ${pretrained_path.${pretrained_source}}
    freeze: False

  classifier:
    proto: Classifier
    num_classes: 14
    use_fc_norm: True
    trunc_init: True
    dropout: 0.

  loss:
    proto: BCEWithLogitsLoss

trainer:
  optimizer: Adam
  optim_params:
    lr: 5e-5
    eps: 1e-08
    optim_groups: ve_only
    lr_multiplier_ve: 0.1
    # weight_decay: 1e-5
  batch_size: 32
  clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 10 # 10 epochs
    t_total: 200 # 200 epochs
  epochs: 200
  early_stop: 10
  eval_start: 10
  eval_interval: 5
  early_stop_metric: multilabel_auroc

validator:
  batch_size: 512
  metrics: [multilabel_accuracy, multilabel_auroc]
  splits: [val]