name: gloria

model:
  cnn:
    proto: VisualEncoder
    backbone: resnet50
    pretrained: /home/faith/unified-framework/ckpt/official/GLoRIA.ckpt
    prefix: gloria.img_encoder.model.
    output_layer: avgpool
    dropout_out: 0.0
    permute: batch_first
    freeze: False

    visual_projection: 
      layer: >
        nn.Linear(2048, 768)
      prefix: gloria.img_encoder.global_embedder.

  language: # for zero-shot experiments
    proto: emilyalsentzer/Bio_ClinicalBERT
    pretrained: /home/faith/unified-framework/ckpt/official/GLoRIA.ckpt
    prefix: gloria.text_encoder.model.
    last_n_layers: 4