name: mrm

model:
  cnn:
    proto: VisualEncoder
    backbone: timmvit
    pretrained: /home/faith/unified-framework/ckpt/pretrained/MRM.pth # no prefix
    dropout_out: 0.0
    drop_path_rate: 0.1
    freeze: False
    num_classes: 0

  language: # for zero-shot experiments
    proto: emilyalsentzer/Bio_ClinicalBERT
    json_file: /home/faith/unified-framework/unifier/blocks/custom/mgca/bert_config.json
    pretrained: /home/faith/unified-framework/ckpt/official/MGCA-vit.ckpt
    prefix: text_encoder_q.model.
    last_n_layers: 4

    language_projection:
      layer: >
        nn.Sequential(
            nn.Linear(768, 2048),
            nn.BatchNorm1d(2048),
            nn.ReLU(inplace=True),
            nn.Linear(2048, 128),
            nn.BatchNorm1d(128, affine=False)
        )
      prefix: text_encoder_q.global_embed.head.