dataset: MIMIC_5x200
transforms: DataTransforms
img_path: /mnt/weka/MedFM/processed_data/mimic_512/
model_name: medclip_vit
tokenizer: emilyalsentzer/Bio_ClinicalBERT
similarity_type: global
mode: retrieval
ckpt_path: /mnt/weka/MedFM/BenchX/ckpt/official/MedCLIP-vit.bin
batch_size: 8
seed: 42
num_workers: 4
device: cuda
