dataset: MIMIC_5x200
transforms: DataTransforms
img_path: /mnt/weka/MedFM/processed_data/mimic_512/
model_name: refers
tokenizer: emilyalsentzer/Bio_ClinicalBERT
similarity_type: global
# similarity_type: local
# similarity_type: both
mode: retrieval
ckpt_path: /mnt/weka/MedFM/BenchX/ckpt/pretrained/REFERS.pth
# ckpt_path: /mnt/weka/MedFM/BenchX/ckpt/official/REFERS.pth
batch_size: 1000
seed: 42
num_workers: 4
device: cuda
