includes:
  - configs/_base_/models/medklip.yml

name: MedKLIP
ckpt_dir: experiments/classification/vindr/
use_amp: True
seed: 42

dataset:
  proto: VinDr_Dataset
  data_path: datasets/VinDr_CXR/
  csvpath: datasets/VinDr_CXR/vindr_labels.csv
  split: "train_1"
  num_workers: 4

transforms:
  type: NIHTransforms

model:
  proto: ImageClassifier

  cnn:
    output_layer: avgpool
    pretrained: checkpoints/MedKLIP.pth
    prefix: module.res_features.
    freeze: False

  classifier:
    proto: Classifier
    # input_size: 768 # overwritten
    num_classes: 14
    dropout: 0.
    # use_fc_norm: False
    # trunc_init: False

  loss:
    proto: BCEWithLogitsLoss

trainer:
  optimizer: Adam
  optim_params:
    lr: 1e-4
    eps: 1e-08
    optim_groups: ve_only
    lr_multiplier_ve: 0.1
    # weight_decay: 1e-5
  batch_size: 64
  clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 50
    t_total: 3000
  epochs: 200
  early_stop: 10
  eval_start: 10
  eval_interval: 5
  early_stop_metric: multilabel_auroc

validator:
  batch_size: 512
  metrics: [multilabel_accuracy, multilabel_auroc]
  splits: [val]