includes:
  - config/templates/finetune/models/mgca_vit.yml

name: MGCA_ViT
ckpt_dir: experiments/classification/siim/
use_amp: True
seed: 42

dataset:
  proto: SIIM_Pneumothorax_Dataset
  data_path: /home/users/astar/ares/zhouy2/scratch/processed_data/siim_acr_pneumothorax
  csvpath: /home/users/astar/ares/zhouy2/scratch/processed_data/siim_acr_pneumothorax/siim_labels.csv
  split: "train_1"
  num_workers: 10

transforms:
  type: NIHTransforms

pretrained_source: official
pretrained_path:
  official: /home/users/astar/ares/zhouy2/scratch/BenchX/ckpt/official/MGCA-vit.ckpt
  custom: /home/users/astar/ares/zhouy2/scratch/BenchX/ckpt/pretrained/MGCA-vit.ckpt
pretrained_prefix:
  official: img_encoder_q.model.
  custom: img_encoder_q.model.

model:
  proto: ImageClassifier

  cnn:
    pretrained: ${pretrained_path.${pretrained_source}}
    prefix: ${pretrained_prefix.${pretrained_source}}
    num_classes: 0  # disable classifier layer
    global_pool: token
    permute: no_permute
    freeze: False

  classifier:
    # proto: Identity
    proto: Classifier
    # use_fc_norm: True
    num_classes: 2
    use_fc_norm: True
    trunc_init: True

  loss:
    proto: CrossEntropyLoss

trainer:
  optimizer: SGD
  optim_params:
    lr: 1e-2
    momentum: 0.9
    optim_groups: ve_only
    lr_multiplier_ve: 0.1
    # weight_decay: 1e-5
  # optimizer: Adam
  # optim_params:
  #   lr: 1e-4
  #   optim_groups: ve_only
  #   lr_multiplier_ve: 0.1
  batch_size: 128
  clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 50
    t_total: 3000
  epochs: 200
  early_stop: 10
  eval_start: 10
  eval_interval: 5
  early_stop_metric: multiclass_f1

validator:
  batch_size: 512
  metrics: [multiclass_accuracy, multiclass_precision, multiclass_recall, multiclass_f1, multiclass_auroc]
  splits: [val]