name: convirt

model:
  cnn:
    proto: VisualEncoder
    backbone: timmvit
    pretrained: /home/faith/unified-framework/ckpt/pretrained/ConVIRT-ViT.pth
    prefix: visual.model.
    dropout_out: 0.0
    freeze: False

    #####  Uncomment below for zero-shot and cls  #####
    # visual_projection: 
    #   layer: >
    #     nn.Sequential(
    #       nn.Linear(projection.visual_embedding_dim, projection.projection_dim),
    #       nn.ReLU(),
    #       nn.Linear(projection.projection_dim, projection.projection_dim),
    #     )
    #   prefix: vis_proj.

  fusion: # for MMVQA
    input_image_embed_size: 768

  transformer: # for RRG
    d_vf: 768

  classifier: # for CLS
    input_size: 768