dataset: MIMIC_5x200
transforms: DataTransforms
img_path: datasets/mimic_512
model_name: mgca
tokenizer: emilyalsentzer/Bio_ClinicalBERT
similarity_type: global
mode: retrieval
ckpt_path: checkpoints/MGCA-resnet50.pth
batch_size: 1000
seed: 42
num_workers: 4
device: cuda