model_name: 'mgca-resnet50'
base_model: 'resnet50'
dataset: 'siim_acr_pneumothorax'
pretrain_path: './checkpoints/MGCA-resnet50.ckpt'
scheduler: 'cosine'
optimizer: 'adamw'
num_steps: 10000
warmup_steps: 500
data_pct: 1
weight_decay: 0.05
learning_rate: 2e-4