#!/bin/bash
#PBS -N BenchX_COVIDx1
#PBS -o log
#PBS -l walltime=48:00:00 
#PBS -l select=1:ngpus=1
#PBS -q ai
#PBS -P 13003832
#PBS -j oe

# Enter the folder where the job script located, if failed, then return the error code.
cd $PBS_O_WORKDIR || exit $?

# If no log folder, then create one
[ -d log ] || mkdir log

# Load any necessary modules or set up your environment
module load miniforge3/23.10 

# Activate your Conda environment
source activate BenchX

# Common parameters
DATASET_NAME="COVIDx" # ["NIH", "VinDr", "CheXpert", "COVIDx", "PadChest"]
COMMON_PARAMS="seed=1 dataset.split=train" # seed = [42, 0, 1]
SUFFIX="" # ["_1", "_10", ""]

# Array of models and their corresponding configurations
declare -a MODELS=(
    "Our_ConVIRT convirt pretrained_source=custom"
    "GLoRIA gloria pretrained_source=official"
    "Our_GLoRIA gloria pretrained_source=custom"
    "MedCLIP_R50 medclip_rn50 pretrained_source=official"
    "MedCLIP_ViT medclip_vit pretrained_source=official"
    "MedKLIP medklip pretrained_source=official"
    "Our_MedKLIP medklip pretrained_source=custom"
    "Our_MFLAG mflag pretrained_source=custom"
    "MGCA_R50 mgca_rn50 pretrained_source=official"
    "Our_MGCA_R50 mgca_rn50 pretrained_source=custom"
    "MGCA_ViT mgca_vit pretrained_source=official"
    "Our_MGCA_ViT mgca_vit pretrained_source=custom"
    "MRM mrm pretrained_source=official"
    "Our_MRM mrm pretrained_source=custom"
    "REFERS refers pretrained_source=official"
    "Our_REFERS refers pretrained_source=custom"
)

# Loop over models and print Python command with specified suffix
for model in "${MODELS[@]}"; do
    set -- $model
    MODEL_NAME=$1
    CONFIG_NAME=$2
    shift 2

    CONFIG_FILE="config/classification/$DATASET_NAME/$CONFIG_NAME.yml"

    # Print the Python command instead of executing it
    echo "python bin/train.py \"$CONFIG_FILE\" name=\"$MODEL_NAME${SUFFIX}\" $COMMON_PARAMS \"$@\""

    python bin/train.py "$CONFIG_FILE" name="$MODEL_NAME${SUFFIX}" trainer.epochs=100 $COMMON_PARAMS "$@"
done