includes:
  - path/to/model/config.yml

name: classification_chexpert
ckpt_dir: ckpt

dataset:
  proto: CheX_Dataset
  imgpath: /VLM/CheXpert-v1.0-small
  data_pct: 0.01

transforms:
  type: CheXTransforms

model:
  proto: ImageClassifier

  cnn:
    output_layer: avgpool # for resnet layers

  classifier:
    proto: Classifier
    # input_size: 768 # overwritten
    num_classes: 13 # No findings are all zero
    dropout: 0.

  loss:
    proto: BCEWithLogitsLoss

trainer:
  optimizer: Adam
  optim_params:
    lr: 0.0005
    weight_decay: 5e-4
  batch_size: 96
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.5
    patience: 1
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: multilabel_auroc

validator:
  batch_size: 16
  metrics: [multilabel_auroc]
  splits: [valid]