includes:
  - path/to/model/config.yml

name: classification_nih
ckpt_dir: ckpt

dataset:
  proto: NIH_Dataset
  imgpath: /VLM/nih_chest_xray/all_classes
  views: ["PA", "AP"]
  data_pct: 0.01

transforms:
  type: NIHTransforms

model:
  proto: ImageClassifier

  cnn:
    output_layer: avgpool # for resnet layers

  classifier:
    proto: Classifier
    # input_size: 768 # overwritten
    num_classes: 14
    dropout: 0.

  loss:
    proto: BCEWithLogitsLoss

trainer:
  optimizer: AdamW
  optim_params:
    lr: 5e-4
    weight_decay: 1e-6
  batch_size: 48
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.5
    patience: 1
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 50
  early_stop: 10
  eval_start: 10
  eval_interval: 10
  early_stop_metric: multilabel_auroc

validator:
  batch_size: 48
  metrics: [multilabel_auroc]
  splits: [valid]