includes:
  - config/templates/finetune/models/gloria.yml

name: segmentation_siim
ckpt_dir: ckpt

dataset:
  proto: SIIM_Pneumothorax_Dataset
  imgpath: /home/faith/MVLM/siim-acr-pneumothorax/dicom-images-train
  pathology_masks: True

transforms:
  type: SegmentationTransforms

model:
  proto: ImageSegmenter
  loss:
    proto: MixedLoss

trainer:
  batch_size: 48
  optimizer: AdamW
  optim_params:
    lr: 5e-4
    weight_decay: 1e-6
  lr_decay: CosineLRScheduler
  lr_decay_params:
    warmup_t: 50
    t_initial: 2000
    warmup_prefix: True
  epochs: 50
  early_stop: 10
  eval_start: 0
  early_stop_metric: medDice
  clip_grad_norm: 1.0

validator:
  batch_size: 48
  metrics:
    - medDice
  splits: [valid]