includes:
  - configs/_base_/models/refers.yml

name: REFERS
ckpt_dir: experiments/classification/covidx/
use_amp: True
seed: 42

dataset:
  proto: COVIDx_Dataset
  data_path: datasets/COVIDx-CXR4
  csvpath: datasets/COVIDx-CXR4/covidx_labels.csv
  split: "train_1"
  num_workers: 16

transforms:
  type: NIHTransforms

model:
  proto: ImageClassifier

  cnn:
    # output_layer: avgpool
    num_classes: 2
    # zero_head: True
    # prelogits: False
    global_pool: token
    prelogits: True
    pretrained: checkpoints/MRM.pth
    prefix: visual.vit.

  classifier:
    # proto: Identity
    proto: Classifier
    # use_fc_norm: True
    num_classes: 2
    use_fc_norm: True
    trunc_init: True

  loss:
    proto: CrossEntropyLoss

trainer:
  # optimizer: SGD
  # optim_params:
  #   lr: 3e-2
  #   momentum: 0.9
  #   optim_groups: ve_only
  #   lr_multiplier_ve: 0.1
  #   # weight_decay: 1e-5
  optimizer: Adam
  optim_params:
    lr: 5e-4
    # optim_groups: ve_only
    # lr_multiplier_ve: 0.1
  batch_size: 64
  clip_grad_norm: 1.0
  lr_decay: WarmupCosineScheduler
  lr_decay_params:
    warmup_steps: 50
    t_total: 3000
  epochs: 200
  early_stop: 10
  eval_start: 10
  eval_interval: 5
  early_stop_metric: multiclass_f1

validator:
  batch_size: 512
  metrics: [multiclass_accuracy, multiclass_precision, multiclass_recall, multiclass_f1, multiclass_auroc]
  splits: [val]